# Generated by Django 4.1.3 on 2022-11-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pto_requests', '0002_alter_ptorequest_hours_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptorequest',
            old_name='employee_number',
            new_name='employee',
        ),
    ]
