# Generated by Django 4.1.3 on 2022-11-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pto_requests', '0003_rename_employee_number_ptorequest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptorequest',
            name='hours_requested',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
