# Generated by Django 4.1.3 on 2022-11-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pto_requests', '0007_remove_ptorequest_employee_ptorequest_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptorequest',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
