# Generated by Django 4.1.3 on 2022-11-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pto_requests', '0008_rename_employee_id_ptorequest_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptorequest',
            old_name='employee',
            new_name='employee_number',
        ),
    ]
