# Generated by Django 4.1.3 on 2022-11-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pto_requests', '0009_rename_employee_ptorequest_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptorequest',
            old_name='employee_number',
            new_name='employee',
        ),
    ]
