# Generated by Django 4.1.3 on 2022-11-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pto_requests', '0010_rename_employee_number_ptorequest_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptorequest',
            name='date_requested',
            field=models.DateField(null=True),
        ),
    ]
