# Generated by Django 4.1.3 on 2023-01-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pto_requests', '0013_alter_ptorequest_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptorequest',
            name='employee',
        ),
    ]
