# Generated by Django 4.1.3 on 2022-12-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisors', '0005_remove_supervisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_id',
        ),
    ]
