# Generated by Django 4.1.3 on 2022-11-09 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('supervisors', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_nubmer', models.IntegerField()),
                ('employee_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=30)),
                ('hire_date', models.DateField()),
                ('active', models.BooleanField()),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supervisors.supervisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
