# Generated by Django 4.1.3 on 2022-11-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pto_balance',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
