# Generated by Django 4.1.3 on 2022-11-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_supervisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_nubmer',
            new_name='employee_number',
        ),
        migrations.AlterField(
            model_name='employee',
            name='pto_balance',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
