# Generated by Django 4.1.3 on 2022-11-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_supervisor_id_employee_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pto_balance',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
