# Generated by Django 4.1.3 on 2022-12-01 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_is_supervisor_alter_employee_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_supervisor',
        ),
    ]
