# Generated by Django 4.1.3 on 2022-12-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_remove_employee_is_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
