# Generated by Django 4.1.3 on 2022-12-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_employee_active_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
