# Generated by Django 4.1.3 on 2023-01-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_employee_active_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='employee',
            name='isSupervisor',
            field=models.BooleanField(default=False, verbose_name='supervisor'),
        ),
    ]
