# Generated by Django 4.1.3 on 2023-01-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_remove_employee_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
